spring:
  config:
    import: "nacos:gateway-service"
  cloud:
    nacos:
      server-addr: 192.168.1.79:8848
      username: nacos
      password: nacos
      discovery:
        group: DEFAULT_GROUP
        namespace: dev
        ephemeral: false
      config:
        group: DEFAULT_GROUP
        namespace: dev

    gateway:
      routes:
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/inventory/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**